// Auto-generated by Supabase MCP `generate_typescript_types` against the
// live production project. To refresh after a migration:
//   1. Apply the migration (via apply_migration).
//   2. Re-run generate_typescript_types.
//   3. Paste the output here (from `export type Json` down to the end
//      of `Constants`).
// Do NOT hand-edit — ergonomic aliases (Profile, Match, etc.) live in
// index.ts so they survive regenerations.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_allowlist: {
        Row: {
          campus_email_domain: string
          created_at: string | null
          email: string
          note: string | null
        }
        Insert: {
          campus_email_domain: string
          created_at?: string | null
          email: string
          note?: string | null
        }
        Update: {
          campus_email_domain?: string
          created_at?: string | null
          email?: string
          note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "admin_allowlist_campus_email_domain_fkey"
            columns: ["campus_email_domain"]
            isOneToOne: false
            referencedRelation: "university_config"
            referencedColumns: ["email_domain"]
          },
        ]
      }
      match_history: {
        Row: {
          id: string
          matched_at: string | null
          user1_id: string
          user2_id: string
        }
        Insert: {
          id?: string
          matched_at?: string | null
          user1_id: string
          user2_id: string
        }
        Update: {
          id?: string
          matched_at?: string | null
          user1_id?: string
          user2_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_history_user1_id_fkey"
            columns: ["user1_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_history_user2_id_fkey"
            columns: ["user2_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      matches: {
        Row: {
          created_at: string | null
          expires_at: string | null
          icebreaker: string | null
          id: string
          status: Database["public"]["Enums"]["match_status"] | null
          user1_id: string
          user2_id: string
        }
        Insert: {
          created_at?: string | null
          expires_at?: string | null
          icebreaker?: string | null
          id?: string
          status?: Database["public"]["Enums"]["match_status"] | null
          user1_id: string
          user2_id: string
        }
        Update: {
          created_at?: string | null
          expires_at?: string | null
          icebreaker?: string | null
          id?: string
          status?: Database["public"]["Enums"]["match_status"] | null
          user1_id?: string
          user2_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "matches_user1_id_fkey"
            columns: ["user1_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_user2_id_fkey"
            columns: ["user2_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          content: string
          created_at: string | null
          id: string
          match_id: string
          sender_id: string
        }
        Insert: {
          content: string
          created_at?: string | null
          id?: string
          match_id: string
          sender_id: string
        }
        Update: {
          content?: string
          created_at?: string | null
          id?: string
          match_id?: string
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          activities: string[] | null
          avatar: string | null
          created_at: string | null
          custom_gender: string | null
          display_alias: string
          email_domain: string
          fcm_token: string | null
          gender: string | null
          hobbies: string[] | null
          id: string
          is_active: boolean | null
          major: string | null
          personality: string[] | null
          updated_at: string | null
          year_in_school: string | null
        }
        Insert: {
          activities?: string[] | null
          avatar?: string | null
          created_at?: string | null
          custom_gender?: string | null
          display_alias: string
          email_domain: string
          fcm_token?: string | null
          gender?: string | null
          hobbies?: string[] | null
          id: string
          is_active?: boolean | null
          major?: string | null
          personality?: string[] | null
          updated_at?: string | null
          year_in_school?: string | null
        }
        Update: {
          activities?: string[] | null
          avatar?: string | null
          created_at?: string | null
          custom_gender?: string | null
          display_alias?: string
          email_domain?: string
          fcm_token?: string | null
          gender?: string | null
          hobbies?: string[] | null
          id?: string
          is_active?: boolean | null
          major?: string | null
          personality?: string[] | null
          updated_at?: string | null
          year_in_school?: string | null
        }
        Relationships: []
      }
      reports: {
        Row: {
          created_at: string | null
          id: string
          match_id: string | null
          reason: string
          reported_user_id: string
          reporter_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          match_id?: string | null
          reason: string
          reported_user_id: string
          reporter_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          match_id?: string | null
          reason?: string
          reported_user_id?: string
          reporter_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_user_id_fkey"
            columns: ["reported_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      university_config: {
        Row: {
          created_at: string | null
          email_domain: string
          timezone: string | null
          university_name: string
        }
        Insert: {
          created_at?: string | null
          email_domain: string
          timezone?: string | null
          university_name: string
        }
        Update: {
          created_at?: string | null
          email_domain?: string
          timezone?: string | null
          university_name?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      check_email_exists: { Args: { email_to_check: string }; Returns: boolean }
      delete_my_account: { Args: never; Returns: undefined }
      expire_active_matches: { Args: never; Returns: undefined }
      is_email_allowed: { Args: { email_to_check: string }; Returns: boolean }
      purge_old_match_history: { Args: never; Returns: undefined }
      validate_edu_email_before_signup: { Args: { event: Json }; Returns: Json }
    }
    Enums: {
      match_status: "active" | "expired" | "unmatched" | "flagged"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
