-- 064 — Load a real wordlist into blocked_terms.
--
-- 056 shipped the filtering mechanism with a 21-word starter list of
-- ordinary profanity and no slurs at all. Hate speech is the actual
-- concern behind App Store guideline 1.2, so that starter list did not
-- back the claim we make to App Review.
--
-- Source: LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words,
-- `en` file (403 entries), curated rather than loaded wholesale:
--
--   * 127 multi-word or punctuated entries dropped. blocked_terms is
--     single-token by CHECK constraint, and mask_blocked_terms matches
--     one token at a time between Postgres word boundaries.
--   * 34 entries removed as unsafe or noisy to block:
--       - identity terms. Masking these would censor students
--         describing themselves, on an app with an Identity field.
--         Slurs aimed at those same groups are kept.
--       - clinical/anatomical words. "breast cancer" and "sex
--         education" are not objectionable content.
--       - everyday collisions a campus chat would hit constantly:
--         garden hoe, Wang as a surname, "that sucks", and "xx",
--         which is how people sign off a message.
--   * 9 major slurs added that the source list omits entirely.
--
--   -> 249 terms, on top of the 21 seeded by 056.
--
-- Word boundaries mean the short entries are safe: "ass" does not fire
-- on assignment, class or pass. Verified against those cases in 056.
--
-- Tune from real data, not guesswork. public.moderation_events records
-- every mask, so a term that fires on innocent messages shows up there
-- and can be deleted from this table with no code change.

INSERT INTO public.blocked_terms (term) VALUES
    ('2g1c'),
    ('acrotomophilia'),
    ('anal'),
    ('anilingus'),
    ('apeshit'),
    ('ass'),
    ('asshole'),
    ('assmunch'),
    ('autoerotic'),
    ('babeland'),
    ('bangbros'),
    ('bangbus'),
    ('bareback'),
    ('barenaked'),
    ('bastard'),
    ('bastardo'),
    ('bastinado'),
    ('bbw'),
    ('bdsm'),
    ('beaner'),
    ('beaners'),
    ('beastiality'),
    ('bestiality'),
    ('bimbos'),
    ('birdlock'),
    ('bitch'),
    ('bitches'),
    ('blowjob'),
    ('blumpkin'),
    ('bollocks'),
    ('boner'),
    ('boob'),
    ('boobs'),
    ('bukkake'),
    ('bulldyke'),
    ('bullshit'),
    ('bunghole'),
    ('busty'),
    ('buttcheeks'),
    ('butthole'),
    ('camgirl'),
    ('camslut'),
    ('camwhore'),
    ('carpetmuncher'),
    ('chink'),
    ('cialis'),
    ('circlejerk'),
    ('clit'),
    ('clusterfuck'),
    ('cock'),
    ('cocks'),
    ('coon'),
    ('coons'),
    ('coprolagnia'),
    ('coprophilia'),
    ('cornhole'),
    ('creampie'),
    ('cum'),
    ('cumming'),
    ('cumshot'),
    ('cumshots'),
    ('cunnilingus'),
    ('cunt'),
    ('darkie'),
    ('daterape'),
    ('deepthroat'),
    ('dendrophilia'),
    ('dick'),
    ('dildo'),
    ('dingleberries'),
    ('dingleberry'),
    ('doggiestyle'),
    ('doggystyle'),
    ('dolcett'),
    ('domination'),
    ('dommes'),
    ('dvda'),
    ('dyke'),
    ('ecchi'),
    ('erotism'),
    ('eunuch'),
    ('fag'),
    ('faggot'),
    ('fecal'),
    ('felch'),
    ('fellatio'),
    ('feltch'),
    ('femdom'),
    ('figging'),
    ('fingerbang'),
    ('fingering'),
    ('fisting'),
    ('footjob'),
    ('frotting'),
    ('fuck'),
    ('fuckin'),
    ('fucking'),
    ('fucktards'),
    ('fudgepacker'),
    ('futanari'),
    ('gangbang'),
    ('goatcx'),
    ('goatse'),
    ('gokkun'),
    ('goodpoop'),
    ('gook'),
    ('goregasm'),
    ('grope'),
    ('guro'),
    ('handjob'),
    ('hardcore'),
    ('hentai'),
    ('homoerotic'),
    ('honkey'),
    ('horny'),
    ('incest'),
    ('intercourse'),
    ('jailbait'),
    ('jigaboo'),
    ('jiggaboo'),
    ('jiggerboo'),
    ('jizz'),
    ('juggs'),
    ('kike'),
    ('kinbaku'),
    ('kinkster'),
    ('knobbing'),
    ('livesex'),
    ('lolita'),
    ('lovemaking'),
    ('masturbate'),
    ('masturbating'),
    ('masturbation'),
    ('milf'),
    ('molester'),
    ('mong'),
    ('motherfucker'),
    ('muffdiving'),
    ('nambla'),
    ('nawashi'),
    ('negro'),
    ('neonazi'),
    ('nigga'),
    ('nigger'),
    ('nimphomania'),
    ('nutten'),
    ('nympho'),
    ('nymphomania'),
    ('octopussy'),
    ('omorashi'),
    ('orgy'),
    ('paedophile'),
    ('paki'),
    ('panties'),
    ('panty'),
    ('pedobear'),
    ('pedophile'),
    ('pegging'),
    ('pikey'),
    ('pissing'),
    ('pisspig'),
    ('playboy'),
    ('ponyplay'),
    ('poof'),
    ('poon'),
    ('poontang'),
    ('poopchute'),
    ('porn'),
    ('porno'),
    ('pornography'),
    ('pthc'),
    ('pubes'),
    ('punany'),
    ('pussy'),
    ('queaf'),
    ('queef'),
    ('quim'),
    ('raghead'),
    ('rape'),
    ('raping'),
    ('rapist'),
    ('rectum'),
    ('retard'),
    ('retarded'),
    ('rimjob'),
    ('rimming'),
    ('sadism'),
    ('santorum'),
    ('scat'),
    ('schlong'),
    ('scissoring'),
    ('sexcam'),
    ('sexuality'),
    ('sexually'),
    ('shemale'),
    ('shibari'),
    ('shit'),
    ('shitblimp'),
    ('shitty'),
    ('shota'),
    ('shrimping'),
    ('skeet'),
    ('slanteye'),
    ('slut'),
    ('smut'),
    ('snowballing'),
    ('sodomize'),
    ('sodomy'),
    ('spastic'),
    ('spic'),
    ('splooge'),
    ('spooge'),
    ('spunk'),
    ('strapon'),
    ('strappado'),
    ('swastika'),
    ('tard'),
    ('threesome'),
    ('throating'),
    ('thumbzilla'),
    ('titties'),
    ('titty'),
    ('topless'),
    ('tosser'),
    ('towelhead'),
    ('tranny'),
    ('tribadism'),
    ('tubgirl'),
    ('tushy'),
    ('twat'),
    ('twink'),
    ('twinkie'),
    ('undressing'),
    ('upskirt'),
    ('urophilia'),
    ('viagra'),
    ('vibrator'),
    ('vorarephilia'),
    ('voyeur'),
    ('voyeurweb'),
    ('voyuer'),
    ('wank'),
    ('wetback'),
    ('whore'),
    ('worldsex'),
    ('xxx'),
    ('yaoi'),
    ('yiffy'),
    ('zoophilia')
ON CONFLICT DO NOTHING;

SELECT count(*) AS total_terms FROM public.blocked_terms;
