-- 064 — Load a curated blocklist of objectionable terms.
--
-- 056 shipped the filtering mechanism with a 21-word starter list that
-- was mostly ordinary profanity and contained no slurs. That is
-- backwards: App Store guideline 1.2 is about objectionable content —
-- slurs, hate speech, sexual violence — not swearing.
--
-- Source: LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words,
-- `en` file (403 entries), curated rather than loaded wholesale:
--
--   * 127 multi-word or punctuated entries dropped. blocked_terms is
--     single-token by CHECK constraint and the matcher works one token
--     at a time between Postgres word boundaries.
--   * identity terms removed. Masking those would censor students
--     describing themselves on an app with an Identity field. Slurs
--     aimed at those same groups are kept.
--   * clinical and anatomical words removed. "breast cancer" and "sex
--     education" are not objectionable content.
--   * everyday collisions removed: garden hoe, Wang as a surname,
--     "that sucks", and "xx", which is how people sign off a message.
--   * 38 ordinary profanity terms removed, variants included. Orbit is a college chat
--     app; students swear, and asterisking "fuck this exam" reads as a
--     bug rather than as moderation. Nothing in 1.2 asks for it.
--   * 9 major slurs added that the source list omits entirely.
--
--   -> 211 terms.
--
-- Deliberately still blocked despite sounding like profanity: cunt,
-- whore, slut. These are used to demean a person rather than as casual
-- swearing. Move them out if you disagree — it's one DELETE.
--
-- Word boundaries keep the short entries safe: nothing here fires on
-- assignment, class or pass.
--
-- Tune from data, not guesswork. moderation_events records every mask,
-- so a term that trips on innocent messages shows up there and can be
-- deleted from this table with no code change and no deploy.

INSERT INTO public.blocked_terms (term) VALUES
    ('2g1c'),
    ('acrotomophilia'),
    ('anal'),
    ('anilingus'),
    ('autoerotic'),
    ('babeland'),
    ('bangbros'),
    ('bangbus'),
    ('bareback'),
    ('barenaked'),
    ('bastinado'),
    ('bbw'),
    ('bdsm'),
    ('beaner'),
    ('beaners'),
    ('beastiality'),
    ('bestiality'),
    ('bimbos'),
    ('birdlock'),
    ('blowjob'),
    ('blumpkin'),
    ('boner'),
    ('bukkake'),
    ('bulldyke'),
    ('bunghole'),
    ('busty'),
    ('buttcheeks'),
    ('butthole'),
    ('camgirl'),
    ('camslut'),
    ('camwhore'),
    ('carpetmuncher'),
    ('chink'),
    ('cialis'),
    ('circlejerk'),
    ('coon'),
    ('coons'),
    ('coprolagnia'),
    ('coprophilia'),
    ('cornhole'),
    ('creampie'),
    ('cumming'),
    ('cumshot'),
    ('cumshots'),
    ('cunnilingus'),
    ('cunt'),
    ('darkie'),
    ('daterape'),
    ('deepthroat'),
    ('dendrophilia'),
    ('dildo'),
    ('dingleberries'),
    ('dingleberry'),
    ('doggiestyle'),
    ('doggystyle'),
    ('dolcett'),
    ('domination'),
    ('dommes'),
    ('dvda'),
    ('dyke'),
    ('ecchi'),
    ('erotism'),
    ('eunuch'),
    ('fag'),
    ('faggot'),
    ('fecal'),
    ('felch'),
    ('fellatio'),
    ('feltch'),
    ('femdom'),
    ('figging'),
    ('fingerbang'),
    ('fingering'),
    ('fisting'),
    ('footjob'),
    ('frotting'),
    ('futanari'),
    ('gangbang'),
    ('goatcx'),
    ('goatse'),
    ('gokkun'),
    ('goodpoop'),
    ('gook'),
    ('goregasm'),
    ('grope'),
    ('guro'),
    ('handjob'),
    ('hardcore'),
    ('hentai'),
    ('homoerotic'),
    ('honkey'),
    ('incest'),
    ('intercourse'),
    ('jailbait'),
    ('jigaboo'),
    ('jiggaboo'),
    ('jiggerboo'),
    ('juggs'),
    ('kike'),
    ('kinbaku'),
    ('kinkster'),
    ('livesex'),
    ('lolita'),
    ('lovemaking'),
    ('masturbate'),
    ('masturbating'),
    ('masturbation'),
    ('milf'),
    ('molester'),
    ('mong'),
    ('muffdiving'),
    ('nambla'),
    ('nawashi'),
    ('negro'),
    ('neonazi'),
    ('nigga'),
    ('nigger'),
    ('nimphomania'),
    ('nutten'),
    ('nympho'),
    ('nymphomania'),
    ('octopussy'),
    ('omorashi'),
    ('orgy'),
    ('paedophile'),
    ('paki'),
    ('panties'),
    ('panty'),
    ('pedobear'),
    ('pedophile'),
    ('pegging'),
    ('pikey'),
    ('playboy'),
    ('ponyplay'),
    ('poof'),
    ('poon'),
    ('poontang'),
    ('poopchute'),
    ('porn'),
    ('porno'),
    ('pornography'),
    ('pthc'),
    ('pubes'),
    ('punany'),
    ('queaf'),
    ('queef'),
    ('quim'),
    ('raghead'),
    ('rape'),
    ('raping'),
    ('rapist'),
    ('rectum'),
    ('retard'),
    ('retarded'),
    ('rimjob'),
    ('rimming'),
    ('sadism'),
    ('santorum'),
    ('scat'),
    ('schlong'),
    ('scissoring'),
    ('sexcam'),
    ('sexuality'),
    ('sexually'),
    ('shemale'),
    ('shibari'),
    ('shota'),
    ('shrimping'),
    ('skeet'),
    ('slanteye'),
    ('slut'),
    ('smut'),
    ('snowballing'),
    ('sodomize'),
    ('sodomy'),
    ('spastic'),
    ('spic'),
    ('splooge'),
    ('spooge'),
    ('spunk'),
    ('strapon'),
    ('strappado'),
    ('swastika'),
    ('tard'),
    ('threesome'),
    ('throating'),
    ('thumbzilla'),
    ('topless'),
    ('towelhead'),
    ('tranny'),
    ('tribadism'),
    ('tubgirl'),
    ('tushy'),
    ('twink'),
    ('twinkie'),
    ('undressing'),
    ('upskirt'),
    ('urophilia'),
    ('viagra'),
    ('vibrator'),
    ('vorarephilia'),
    ('voyeur'),
    ('voyeurweb'),
    ('voyuer'),
    ('wetback'),
    ('whore'),
    ('worldsex'),
    ('xxx'),
    ('yaoi'),
    ('yiffy'),
    ('zoophilia')
ON CONFLICT DO NOTHING;

-- Drop the casual profanity 056 seeded.
DELETE FROM public.blocked_terms WHERE term IN (
    'apeshit', 'asshole', 'assmunch', 'bastard', 'bastardo', 'bitch', 'bullshit', 'clit', 'clusterfuck', 'cock', 'dick', 'douchebag', 'fuck', 'fucker', 'fuckin', 'fucking', 'fucktards', 'knobbing', 'motherfucker', 'pissing', 'pisspig', 'pussy', 'shit', 'shitblimp', 'titties', 'titty'
);

SELECT count(*) AS total_terms FROM public.blocked_terms;
