-- 064 — A blocklist of actually objectionable terms.
--
-- REWRITTEN. The first version of this file derived from LDNOOBW, and
-- that was the wrong source: it's a list built to filter porn-site
-- keywords, not hate speech. After three rounds of patching it still
-- contained panty, vibrator, threesome and hardcore — 41 of 211 terms
-- were porn vocabulary, none of which is objectionable content under
-- App Store guideline 1.2, and all of which would mask normal
-- conversation between adults on an 18+ app.
--
-- So this is built by category instead, from what 1.2 actually means:
--
--   racial / ethnic slurs    42
--   LGBTQ+ slurs             16
--   ableist slurs            10
--   sexual violence          12
--   child exploitation       13
--   gendered abuse            6
--   ----------------------------
--   total                    99
--
-- Deliberately NOT here: profanity (fuck, shit, horny), anatomy (penis,
-- breast), sexual vocabulary between consenting adults (porn, vibrator,
-- threesome), and identity words (gay, lesbian, trans, queer). None of
-- those are objectionable content; masking them makes the app look
-- broken and, in the case of identity words, actively harmful.
--
-- Collision-prone terms were left out on purpose even though they are
-- slurs in some usage: cracker, spook, fairy, gyp, cripple. Each has a
-- common innocent meaning and word boundaries can't disambiguate.
--
-- The judgment call worth revisiting: the six gendered-abuse terms
-- (cunt, whore, slut and plurals). They're aimed at a person rather
-- than used as general swearing, which is why they're in. One DELETE
-- if you disagree.
--
-- This REPLACES the table contents rather than adding to it, so it's
-- idempotent and also clears 056's starter seed.

DELETE FROM public.blocked_terms
WHERE term <> ALL (ARRAY[
    'beaner',
    'beaners',
    'bestiality',
    'childporn',
    'chink',
    'chinks',
    'coon',
    'coons',
    'cunt',
    'cunts',
    'dago',
    'dagos',
    'darkie',
    'darky',
    'dyke',
    'dykes',
    'fag',
    'faggot',
    'faggots',
    'faggy',
    'fags',
    'fudgepacker',
    'gook',
    'gooks',
    'halfbreed',
    'homo',
    'homos',
    'incest',
    'injun',
    'jailbait',
    'jigaboo',
    'kike',
    'kikes',
    'ladyboy',
    'lolicon',
    'molest',
    'molested',
    'molester',
    'molesting',
    'mong',
    'mongoloid',
    'necrophilia',
    'nigga',
    'niggas',
    'nigger',
    'niggers',
    'niglet',
    'paedophile',
    'paedophiles',
    'paedophilia',
    'paki',
    'pakis',
    'pedo',
    'pedophile',
    'pedophiles',
    'pedophilia',
    'pedos',
    'pickaninny',
    'polack',
    'poofter',
    'pthc',
    'raghead',
    'ragheads',
    'rape',
    'rapes',
    'raping',
    'rapist',
    'rapists',
    'redskin',
    'retard',
    'retarded',
    'retards',
    'sambo',
    'shemale',
    'shemales',
    'shotacon',
    'slanteye',
    'slut',
    'sluts',
    'spastic',
    'spaz',
    'spazz',
    'spic',
    'spics',
    'squaw',
    'tarbaby',
    'tard',
    'tards',
    'towelhead',
    'towelheads',
    'trannies',
    'tranny',
    'wetback',
    'wetbacks',
    'whore',
    'whores',
    'wop',
    'wops',
    'zipperhead'
]);

INSERT INTO public.blocked_terms (term) VALUES
    ('beaner'),
    ('beaners'),
    ('bestiality'),
    ('childporn'),
    ('chink'),
    ('chinks'),
    ('coon'),
    ('coons'),
    ('cunt'),
    ('cunts'),
    ('dago'),
    ('dagos'),
    ('darkie'),
    ('darky'),
    ('dyke'),
    ('dykes'),
    ('fag'),
    ('faggot'),
    ('faggots'),
    ('faggy'),
    ('fags'),
    ('fudgepacker'),
    ('gook'),
    ('gooks'),
    ('halfbreed'),
    ('homo'),
    ('homos'),
    ('incest'),
    ('injun'),
    ('jailbait'),
    ('jigaboo'),
    ('kike'),
    ('kikes'),
    ('ladyboy'),
    ('lolicon'),
    ('molest'),
    ('molested'),
    ('molester'),
    ('molesting'),
    ('mong'),
    ('mongoloid'),
    ('necrophilia'),
    ('nigga'),
    ('niggas'),
    ('nigger'),
    ('niggers'),
    ('niglet'),
    ('paedophile'),
    ('paedophiles'),
    ('paedophilia'),
    ('paki'),
    ('pakis'),
    ('pedo'),
    ('pedophile'),
    ('pedophiles'),
    ('pedophilia'),
    ('pedos'),
    ('pickaninny'),
    ('polack'),
    ('poofter'),
    ('pthc'),
    ('raghead'),
    ('ragheads'),
    ('rape'),
    ('rapes'),
    ('raping'),
    ('rapist'),
    ('rapists'),
    ('redskin'),
    ('retard'),
    ('retarded'),
    ('retards'),
    ('sambo'),
    ('shemale'),
    ('shemales'),
    ('shotacon'),
    ('slanteye'),
    ('slut'),
    ('sluts'),
    ('spastic'),
    ('spaz'),
    ('spazz'),
    ('spic'),
    ('spics'),
    ('squaw'),
    ('tarbaby'),
    ('tard'),
    ('tards'),
    ('towelhead'),
    ('towelheads'),
    ('trannies'),
    ('tranny'),
    ('wetback'),
    ('wetbacks'),
    ('whore'),
    ('whores'),
    ('wop'),
    ('wops'),
    ('zipperhead')
ON CONFLICT DO NOTHING;

SELECT count(*) AS total_terms FROM public.blocked_terms;
